import { CompetencyTeachingDefinition, TeachingEventDef } from '../types';

/**
 * CANONICAL TEACHING DEFINITIONS
 * Typed instructional metadata driving the 6-stage continuum:
 * UNDERSTAND -> COUNT -> WATCH -> FOLLOW -> PLAY -> EVALUATE
 */

export const TEACHING_DEFINITIONS: Record<string, CompetencyTeachingDefinition> = {
  // 1. QUARTER-NOTE PULSE STABILITY
  'comp-pulse-quarter': {
    id: 'teach-pulse-quarter',
    competencyId: 'comp-pulse-quarter',
    skillId: 'time-quarter-pulse',
    title: 'Quarter-Note Pulse Stability',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: 'Quarter Notes',
    subdivisionCount: 1,
    countTokens: ['1', '2', '3', '4'],
    spokenTokens: ['one', 'two', 'three', 'four'],
    sticking: 'R R R R',
    limbPattern: 'Lead hand (Right or Left) tapping steady downbeats',
    drumSurfaces: ['Pad Center', 'Snare Drum', 'Floor Tom / Ride Bell'],
    accentPositions: [0], // Beat 1 accented
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>1', description: 'Downbeat anchor' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'pad_center', accent: false, label: '2', description: 'Steady pulse' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: false, label: '3', description: 'Center pulse' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'pad_center', accent: false, label: '4', description: 'Upbeat resolution' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Quarter-Note Pulse Stability trains your internal clock to land squarely on the metronome click with zero dragging or rushing.',
      howIsItCounted: 'Count out loud: "1 - 2 - 3 - 4" with an open, relaxed voice on every single click.',
      handsAndFeet: 'Use your dominant hand (R) or alternating hands. Keep your wrist loose and stroke height consistent (approx. 6-8 inches).',
      drumSurfaces: 'On pad: center tap for maximum clarity. On drum kit: snare center or closed hi-hat.',
      musicalApplication: 'Every pop, rock, worship, and funk song relies on the drummer being completely locked into this steady downbeat pulse.',
      whatToListenFor: 'Listen for your stick sound "flamming" (doubling) against the click. The click should completely disappear beneath your stroke.',
    },
    commonMistakes: [
      'Rushing ahead of the click when counting silently',
      'Tensing shoulders and gripping the stick too tightly',
      'Accelerating during the space between beats 2 and 3',
    ],
    diagnosticIssues: ['Lost pulse', 'Rushed', 'Dragged', 'Tension', 'Uneven notes'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 30,
      standardText: 'Quarter notes at 80 BPM for 30 seconds with zero timing drift',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 2. EIGHTH-NOTE SUBDIVISION COUNTING
  'comp-subdiv-8th': {
    id: 'teach-subdiv-8th',
    competencyId: 'comp-subdiv-8th',
    skillId: 'time-8th-subdivision',
    title: 'Eighth-Note Subdivision Counting',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'and'],
    sticking: 'R L R L R L R L',
    limbPattern: 'Alternating hands (Right leads downbeats, Left plays upbeats)',
    drumSurfaces: ['Pad Center', 'Closed Hi-Hat', 'Snare'],
    accentPositions: [0, 4], // Beat 1 and 3
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Beat 1 Downbeat' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 1 Upbeat (&)' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 2 Downbeat' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 2 Upbeat (&)' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Beat 3 Downbeat' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 3 Upbeat (&)' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 4 Downbeat' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 4 Upbeat (&)' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Subdividing the space between pulses into two equal halves ("1 & 2 & 3 & 4 &").',
      howIsItCounted: 'Say "1 and 2 and 3 and 4 and" out loud. The numbers line up with the click; the "and" sits exactly in the middle.',
      handsAndFeet: 'Right hand on the numbers (1, 2, 3, 4), Left hand on the "and" (&). Smooth alternating motion.',
      drumSurfaces: 'Practice pad or closed hi-hat. Keep volume identical between left and right hands.',
      musicalApplication: 'The foundation for classic straight-8th rock, pop, worship, and country grooves.',
      whatToListenFor: 'Listen for equal distance between each note. Do not swing or limp (dotted rhythm).',
    },
    commonMistakes: [
      'Swinging the 8th notes instead of keeping them straight and even',
      'Left hand playing softer or rushing the "&"',
      'Losing count on beat 3',
    ],
    diagnosticIssues: ['Lost pulse', 'Rushed', 'Dragged', 'Uneven notes', 'Wrong sticking'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 30,
      standardText: '8th notes at 75 BPM for 30 seconds with even dynamic spacing',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 3. UNDERSTANDING 4/4 BAR STRUCTURE
  'comp-meter-44': {
    id: 'teach-meter-44',
    competencyId: 'comp-meter-44',
    skillId: 'time-44',
    title: 'Understanding 4/4 Bar Structure',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: 'Quarter Notes',
    subdivisionCount: 1,
    countTokens: ['1', '2', '3', '4'],
    spokenTokens: ['one', 'two', 'three', 'four'],
    sticking: 'R R R R',
    limbPattern: 'One relaxed pulse per beat; Beat 1 marks the start of each new bar',
    drumSurfaces: ['Hi-Hat / Ride', 'Practice Pad'],
    accentPositions: [0], // Slight Beat-1 landmark only — no fill/crash choreography
    bars: 2,
    events: [
      // Keep this competency deliberately neutral: the task is bar awareness,
      // not a groove, fill, crash landing, or limb-independence test.
      { bar: 1, beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'hihat_closed', accent: true, label: 'Bar 1 (1)', description: 'Bar 1 Beat 1 — bar-start landmark' },
      { bar: 1, beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'hihat_closed', accent: false, label: '2', description: 'Bar 1 Beat 2' },
      { bar: 1, beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'hihat_closed', accent: false, label: '3', description: 'Bar 1 Beat 3' },
      { bar: 1, beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'hihat_closed', accent: false, label: '4', description: 'Bar 1 Beat 4' },
      // Bar 2 repeats the same pulse. Beat 1 is a structural reset, not a crash landing.
      { bar: 2, beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'hihat_closed', accent: true, label: 'Bar 2 (1)', description: 'Bar 2 Beat 1 — new-bar reset' },
      { bar: 2, beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'hihat_closed', accent: false, label: '2', description: 'Bar 2 Beat 2' },
      { bar: 2, beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'hihat_closed', accent: false, label: '3', description: 'Bar 2 Beat 3' },
      { bar: 2, beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'hihat_closed', accent: false, label: '4', description: 'Bar 2 Beat 4' },
    ],
    musicalExplanation: {
      whatAmILearning: '4/4 time means four quarter-note beats make up one measure (bar). Beat 1 is the structural reset point.',
      howIsItCounted: 'Count "1 2 3 4" continuously while also knowing which bar you are in. Beat 1 begins each new bar.',
      handsAndFeet: 'Use one relaxed hand on a pad, hi-hat, or ride for one pulse per beat. No fill or crash is required.',
      drumSurfaces: 'Practice Pad, Hi-Hat, or Ride. Keep the sound simple so attention stays on bar and phrase structure.',
      musicalApplication: 'Most worship, pop, rock, and funk arrangements are organised in repeating 4/4 bars. Tracking bars lets you recognise phrases and section changes.',
      whatToListenFor: 'Feel Beat 1 as the beginning of a new bar without changing tempo. Know both the beat number and the bar number.',
    },
    commonMistakes: [
      'Losing track of whether you are in Bar 1, Bar 2, Bar 3, or Bar 4',
      'Dropping beat 4 before the next bar begins',
      'Restarting the count early instead of completing all four beats',
    ],
    diagnosticIssues: ['Lost track of bar number', 'Dropped beat 4', 'Rushed barline', 'Lost pulse'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 48,
      standardText: '16 bars in 4/4 time at 80 BPM with perfect phrase tracking',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 4. DRUM NOTATION BASICS
  'comp-reading-notation': {
    id: 'teach-reading-notation',
    competencyId: 'comp-reading-notation',
    skillId: 'read-notation-basics',
    title: 'Drum Notation Basics (Kick, Snare, Hats)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'and'],
    sticking: 'R K R L R K R L',
    limbPattern: 'Coordinated limbs mapped to staff positions',
    drumSurfaces: ['Kick', 'Snare', 'Closed Hi-Hat'],
    accentPositions: [2, 6], // Snare on 2 and 4
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'BOTH', surface: 'kick', accent: true, label: 'K+H', description: 'Kick (bottom space) + Hat (top line)' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat (top line "x")' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'BOTH', surface: 'snare', accent: true, label: 'S+H', description: 'Snare (3rd space) + Hat' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'BOTH', surface: 'kick', accent: false, label: 'K+H', description: 'Kick + Hat' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'BOTH', surface: 'snare', accent: true, label: 'S+H', description: 'Snare + Hat' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat' },
    ],
    musicalExplanation: {
      whatAmILearning: 'How drum notation maps to the instrument: Kick is bottom space, Snare is middle (3rd space), Hi-Hat is top line with an "x".',
      howIsItCounted: 'Count "1 & 2 & 3 & 4 &" while visually connecting each notehead to your limbs.',
      handsAndFeet: 'Right foot on kick, Left hand on snare, Right hand on hi-hat.',
      drumSurfaces: 'Full kit voices (Kick, Snare, Closed Hat). Pad users play low tap for kick, center for snare, edge for hat.',
      musicalApplication: 'Reading charts and method books allows you to learn songs and rudiments independently.',
      whatToListenFor: 'Clean unisons when limbs strike simultaneously. No flamming between hand and foot.',
    },
    commonMistakes: [
      'Flamming the kick and hi-hat on beat 1',
      'Confusing snare and kick noteheads on the staff',
      'Stopping the hi-hat hand when the kick strikes',
    ],
    diagnosticIssues: ['Kick coordination', 'Wrong sticking', 'Uneven notes', 'Lost pulse'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 70,
      durationSeconds: 30,
      standardText: 'Sight-read 8 bars of basic notation at 70 BPM',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: false,
  },

  // 5. BACKBEAT CONCEPT & PLACEMENT
  'comp-grv-backbeat': {
    id: 'teach-grv-backbeat',
    competencyId: 'comp-grv-backbeat',
    skillId: 'grv-backbeat',
    title: 'Backbeat Concept & Placement',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'TWO', 'and', 'three', 'and', 'FOUR', 'and'],
    sticking: 'R R R+L R R R R+L R',
    limbPattern: 'RH maintains steady 8th-note hi-hat, LH delivers powerful backbeats on 2 and 4',
    drumSurfaces: ['Snare', 'Closed Hi-Hat', 'Kick'],
    accentPositions: [2, 6], // Beats 2 and 4
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat 1' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat &' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], accent: true, label: '>SNARE (2)', description: 'Backbeat 2 snap' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat &' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat 3' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat &' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], accent: true, label: '>SNARE (4)', description: 'Backbeat 4 snap' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: 'H', description: 'Hi-Hat &' },
    ],
    musicalExplanation: {
      whatAmILearning: 'The backbeat on Beats 2 and 4 is the heartbeat of rock, pop, and worship. It anchors the entire band.',
      howIsItCounted: 'Emphasize beats 2 and 4 vocally: "1 - TWO - 3 - FOUR".',
      handsAndFeet: 'Left hand drops from 10-12 inches on beats 2 and 4. Right hand plays relaxed 8th notes on hi-hat.',
      drumSurfaces: 'Crisp center snare hit (or rimshot) with closed hi-hat.',
      musicalApplication: 'Makes people dance and headbob. A weak or rushed backbeat instantly destabilizes the music.',
      whatToListenFor: 'A deep, consistent pop on beats 2 and 4. Check that beat 2 does not sound louder than beat 4.',
    },
    commonMistakes: [
      'Rushing into beat 2 because of nervous energy',
      'Letting the hi-hat choke or stop when striking the snare',
      'Inconsistent velocity between backbeat 2 and backbeat 4',
    ],
    diagnosticIssues: ['Rushed', 'Tension', 'Uneven notes', 'Lost pulse'],
    workingTempo: 70,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 30,
      standardText: '8th notes at 80 BPM for 30 seconds with unwavering snare on 2 & 4',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 6. GROOVE STABILITY & POCKET (BASIC 4/4 GROOVE)
  'comp-grv-stability': {
    id: 'teach-grv-stability',
    competencyId: 'comp-grv-stability',
    skillId: 'grv-stability',
    title: 'Basic 4/4 Groove & Pocket Stability',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'and'],
    sticking: 'K+H H S+H H K+H H S+H H',
    limbPattern: 'Three-way coordination: RF Kick on 1 & 3, LH Snare on 2 & 4, RH Hi-Hat on all 8ths',
    drumSurfaces: ['Kick', 'Snare', 'Closed Hi-Hat'],
    accentPositions: [2, 6],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'hihat_closed'], accent: true, label: 'Kick (1)', description: 'Downbeat Kick + Hat' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat tap' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], accent: true, label: 'Snare (2)', description: 'Backbeat Snare + Hat' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat tap' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'hihat_closed'], accent: false, label: 'Kick (3)', description: 'Kick + Hat' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat tap' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], accent: true, label: 'Snare (4)', description: 'Backbeat Snare + Hat' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat tap' },
    ],
    musicalExplanation: {
      whatAmILearning: 'The foundational drum beat of modern music: Bass drum on 1 and 3, Snare drum on 2 and 4, steady 8th-note Hi-Hat.',
      howIsItCounted: 'Count "1 & 2 & 3 & 4 &" continuously while playing.',
      handsAndFeet: 'Right Hand plays all 8 beats on Hi-Hat. Right Foot drops Kick on 1 and 3. Left Hand snaps Snare on 2 and 4.',
      drumSurfaces: 'Kick, Snare, Closed Hi-Hat.',
      musicalApplication: 'Heard on thousands of classic tracks from Queen to Michael Jackson to Coldplay.',
      whatToListenFor: 'Balance: Hi-hat should not overpower the snare and kick. All 3 limbs must sound like one cohesive drum set.',
    },
    commonMistakes: [
      'Flamming kick and hi-hat on beat 3',
      'Hi-hat volume too loud compared to snare and kick',
      'Speeding up slightly on beat 3 and 4',
    ],
    diagnosticIssues: ['Kick coordination', 'Lost pulse', 'Rushed', 'Uneven notes'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 48,
      standardText: '16 unbroken bars at 75 BPM with metronome',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 7. BASIC KICK VARIATIONS
  'comp-grv-kick-variation': {
    id: 'teach-kick-variation',
    competencyId: 'comp-grv-kick-variation',
    skillId: 'grv-kick-variation',
    title: 'Basic Kick Variations (Syncopated Bass Drum)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'and'],
    sticking: 'K+H H S+H K+H K+H H S+H H',
    limbPattern: 'Syncopated kick on the "&" of 2 (leading into beat 3)',
    drumSurfaces: ['Kick', 'Snare', 'Closed Hi-Hat'],
    accentPositions: [2, 6],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'hihat_closed'], accent: true, label: 'Kick (1)', description: 'Kick on 1' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat &' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], accent: true, label: 'Snare (2)', description: 'Backbeat 2' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'hihat_closed'], accent: false, label: 'Kick (&)', description: 'Syncopated Kick on "&"' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'hihat_closed'], accent: false, label: 'Kick (3)', description: 'Downbeat Kick 3' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat &' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], accent: true, label: 'Snare (4)', description: 'Backbeat 4' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Hi-Hat &' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Moving the bass drum off the downbeat to the upbeat ("&" of beat 2), creating funk, rock, and pop momentum.',
      howIsItCounted: 'Count "1 & 2 [&] 3 & 4 &". Pay special attention to hitting the kick exactly on the "&" of 2.',
      handsAndFeet: 'Right foot strikes with right hand on the "&" of beat 2 immediately after the snare backbeat.',
      drumSurfaces: 'Kick, Snare, Closed Hi-Hat.',
      musicalApplication: 'Creates forward motion in rock anthems, funk grooves, and upbeat pop songs.',
      whatToListenFor: 'The kick on "&" must not pull the hi-hat out of time. Clean unison between hand and foot.',
    },
    commonMistakes: [
      'Dragging the kick on the "&" of 2',
      'Accidentally playing the snare late on beat 2 because anticipation of the kick',
      'Right foot tension when playing two kicks in close succession',
    ],
    diagnosticIssues: ['Kick coordination', 'Dragged', 'Rushed', 'Lost pulse'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 30,
      standardText: '8 bars of kick variation groove at 75 BPM',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 8. QUARTER-NOTE FILL
  'comp-fill-quarter': {
    id: 'teach-fill-quarter',
    competencyId: 'comp-fill-quarter',
    skillId: 'fill-quarter',
    title: 'Quarter-Note Fill (4-Beat Tom Movement)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: 'Quarter Notes',
    subdivisionCount: 1,
    countTokens: ['1', '2', '3', '4'],
    spokenTokens: ['one', 'two', 'three', 'four'],
    sticking: 'R R R R (or R L R L)',
    limbPattern: 'Moving across toms on downbeats: Snare -> High Tom -> Mid Tom -> Floor Tom',
    drumSurfaces: ['Snare', 'High Tom', 'Mid Tom', 'Floor Tom', 'Crash'],
    accentPositions: [0],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'snare', accent: true, label: 'Snare (1)', description: 'Fill Entry: Snare Beat 1' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'tom_high', accent: false, label: 'High Tom (2)', description: 'High Tom Beat 2' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'tom_mid', accent: false, label: 'Mid Tom (3)', description: 'Mid Tom Beat 3' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'tom_floor', accent: false, label: 'Floor Tom (4)', description: 'Floor Tom Beat 4' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Navigating the drum kit spatially on quarter notes before playing faster fills. Moving your hands cleanly between drums.',
      howIsItCounted: 'Count "1 - 2 - 3 - 4" with solid, authoritative voice.',
      handsAndFeet: 'Use right hand leading. Lift the stick high enough to clear rims smoothly.',
      drumSurfaces: 'Snare (1) -> Tom 1 (2) -> Tom 2 (3) -> Floor Tom (4) -> Crash on next Beat 1.',
      musicalApplication: 'Used in building stadium rock fills, ballad transitions, and worship section lifts.',
      whatToListenFor: 'Equal tone and volume across every drum. Avoid rushing beat 4 as you head toward the crash.',
    },
    commonMistakes: [
      'Hitting the rim of the toms during transit',
      'Rushing beat 4 to reach the crash cymbal early',
      'Dropping stick velocity on the floor tom',
    ],
    diagnosticIssues: ['Missed beat 1', 'Rushed', 'Lost the groove after the fill', 'Tension'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 30,
      standardText: 'Execute 4-beat quarter fill into downbeat crash at 75 BPM',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 9. EIGHTH-NOTE FILL
  'comp-fill-8th': {
    id: 'teach-fill-8th',
    competencyId: 'comp-fill-8th',
    skillId: 'fill-8th',
    title: 'Eighth-Note Fill & Orchestration',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'and'],
    sticking: 'R L R L R L R L',
    limbPattern: 'Alternating strokes moving from Snare to High Tom to Floor Tom',
    drumSurfaces: ['Snare', 'High Tom', 'Floor Tom', 'Crash'],
    accentPositions: [0],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'snare', accent: true, label: '>R', description: 'Snare 1' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'L', surface: 'snare', accent: false, label: 'L', description: 'Snare &' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'snare', accent: false, label: 'R', description: 'Snare 2' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'L', surface: 'snare', accent: false, label: 'L', description: 'Snare &' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'tom_high', accent: false, label: 'R', description: 'High Tom 3' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'L', surface: 'tom_high', accent: false, label: 'L', description: 'High Tom &' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'tom_floor', accent: false, label: 'R', description: 'Floor Tom 4' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'L', surface: 'tom_floor', accent: false, label: 'L', description: 'Floor Tom &' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Playing continuous alternating 8th notes across drums to signal a song section change.',
      howIsItCounted: 'Count "1 & 2 & 3 & 4 &" maintaining tempo without speeding up during the fill.',
      handsAndFeet: 'Alternating hands (R L R L). Both arms travel smoothly from center snare to right-side floor tom.',
      drumSurfaces: 'Snare on 1 & 2, High Tom on 3, Floor Tom on 4.',
      musicalApplication: 'The standard energetic transition from verse to chorus in rock and pop.',
      whatToListenFor: 'Smooth dynamic continuity. Do not allow the toms to sound dramatically quieter than the snare.',
    },
    commonMistakes: [
      'Accelerating when entering the fill on beat 1 or beat 3',
      'Left hand hesitating during the movement from snare to tom',
      'Failing to land on Beat 1 of the following bar with Crash + Kick',
    ],
    diagnosticIssues: ['Rushed', 'Missed beat 1', 'Lost the groove after the fill', 'Wrong sticking'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 30,
      standardText: '8th-note fill with clean beat 1 recovery at 75 BPM',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 10. SIXTEENTH-NOTE FILL
  'comp-fill-16th': {
    id: 'teach-fill-16th',
    competencyId: 'comp-fill-16th',
    skillId: 'fill-16th',
    title: 'Sixteenth-Note Fill (Beat 4 Entry)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '16th Notes',
    subdivisionCount: 4,
    countTokens: ['4', 'e', '&', 'a'],
    spokenTokens: ['four', 'e', 'and', 'a'],
    sticking: 'R L R L',
    limbPattern: 'Rapid 4-stroke single roll on Beat 4 leading directly to Beat 1 Crash',
    drumSurfaces: ['Snare', 'Crash', 'Kick'],
    accentPositions: [0], // Beat 4 accent
    bars: 1,
    events: [
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'snare', accent: true, label: '>R (4)', description: 'Fill Entry Landmark on 4' },
      { beat: 4, subdivision: 1, countToken: 'e', hand: 'L', surface: 'snare', accent: false, label: 'L (e)', description: 'Inner stroke e' },
      { beat: 4, subdivision: 2, countToken: '&', hand: 'R', surface: 'snare', accent: false, label: 'R (&)', description: 'Inner stroke &' },
      { beat: 4, subdivision: 3, countToken: 'a', hand: 'L', surface: 'snare', accent: false, label: 'L (a)', description: 'Inner stroke a' },
    ],
    musicalExplanation: {
      whatAmILearning: 'The classic 1-beat 16th fill: four quick, even notes on Beat 4 ("4-e-and-a") resolving into the next bar.',
      howIsItCounted: 'Count "1 & 2 & 3 & 4-e-&-a -> 1!". The subdivision quadruples on beat 4.',
      handsAndFeet: 'Right leads on 4, Left on e, Right on &, Left on a. Right hand and right foot land on Beat 1 Crash + Kick.',
      drumSurfaces: 'Snare drum (or high tom) for the 4 strokes, resolving to Crash Cymbal + Kick drum.',
      musicalApplication: 'Used in virtually every drum track to punctuate musical phrases without interrupting groove flow.',
      whatToListenFor: 'Crisp, mathematically even 16th notes. Avoid scrambling or cramming the notes at the end of beat 4.',
    },
    commonMistakes: [
      'Entering Beat 4 too early or late',
      'Dragging the "a" and missing the downbeat crash',
      'Dropping backbeat groove tempo before the fill',
    ],
    diagnosticIssues: ['Missed beat 1', 'Rushed', 'Dragged', 'Lost the groove after the fill'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 70,
      durationSeconds: 30,
      standardText: '1-beat 16th fill with instant groove recovery at 70 BPM',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 11. GROOVE-TO-FILL TRANSITION
  'comp-fill-entry': {
    id: 'teach-fill-entry',
    competencyId: 'comp-fill-entry',
    skillId: 'fill-entry',
    title: 'Groove-to-Fill Transition Mechanics',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '16th Notes',
    subdivisionCount: 4,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', 'e', '&', 'a'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'e', 'and', 'a'],
    sticking: 'K+H H S+H H K+H H R L R L',
    limbPattern: 'Transition from 3 beats of steady groove directly into Beat 4 fill without tempo hitch',
    drumSurfaces: ['Kick', 'Snare', 'Closed Hi-Hat'],
    accentPositions: [6], // Beat 4 entry
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'BOTH', surface: 'kick', accent: true, label: 'Groove 1', description: 'Groove Kick' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'BOTH', surface: 'snare', accent: true, label: 'Groove 2', description: 'Groove Snare' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'BOTH', surface: 'kick', accent: false, label: 'Groove 3', description: 'Groove Kick' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'snare', accent: true, label: 'Fill 4', description: 'Fill Entry Landmark' },
      { beat: 4, subdivision: 1, countToken: 'e', hand: 'L', surface: 'snare', accent: false, label: 'e', description: 'Inner stroke' },
      { beat: 4, subdivision: 2, countToken: '&', hand: 'R', surface: 'snare', accent: false, label: '&', description: 'Inner stroke' },
      { beat: 4, subdivision: 3, countToken: 'a', hand: 'L', surface: 'snare', accent: false, label: 'a', description: 'Inner stroke' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Eliminating the "hitch" or hesitation that occurs when drummers switch mental gears from playing time to playing a fill.',
      howIsItCounted: 'Internalize the 16th-note grid on beats 1, 2, and 3 so beat 4 arrives naturally.',
      handsAndFeet: 'Right hand seamlessly lifts off the hi-hat on beat 3-and to target the snare for beat 4.',
      drumSurfaces: 'Hi-Hat / Kick / Snare transitioning to Snare fill.',
      musicalApplication: 'Professional drummers sound authoritative because their transitions are completely smooth.',
      whatToListenFor: 'Metronome continuity. The metronome click on beat 4 must land exactly on the first note of your fill.',
    },
    commonMistakes: [
      'Pausing or hesitating right before Beat 4',
      'Right hand hitting both the hi-hat and snare on Beat 4',
      'Speeding up on beat 3 in anticipation',
    ],
    diagnosticIssues: ['Rushed', 'Dragged', 'Lost pulse', 'Tension'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 70,
      durationSeconds: 30,
      standardText: 'Flawless groove-to-fill entry with zero tempo micro-deviation',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 12. FILL-TO-GROOVE BEAT-1 RECOVERY
  'comp-fill-recovery': {
    id: 'teach-fill-recovery',
    competencyId: 'comp-fill-recovery',
    skillId: 'fill-recovery',
    title: 'Fill-to-Groove Beat-1 Recovery',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '8th Notes',
    subdivisionCount: 2,
    countTokens: ['1', '&', '2', '&', '3', '&', '4', '&'],
    spokenTokens: ['one', 'and', 'two', 'and', 'three', 'and', 'four', 'and'],
    sticking: 'BOTH H S+H H K+H H S+H H',
    limbPattern: 'Crash + Kick landing on Beat 1, followed immediately by steady groove on Beat 2',
    drumSurfaces: ['Crash', 'Kick', 'Snare', 'Closed Hi-Hat'],
    accentPositions: [0],
    bars: 1,
    events: [
      // Landing bar
      { beat: 1, subdivision: 0, countToken: '1', hand: 'BOTH', surface: 'crash', surfaces: ['crash', 'kick'], role: 'landing', accent: true, label: '💥 CRASH + KICK (1)', description: 'Downbeat Landing Target' },
      { beat: 1, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Return to Hi-Hat' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], role: 'groove_return', accent: true, label: 'Snare (2)', description: 'Immediate backbeat recovery' },
      { beat: 2, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Steady groove' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'hihat_closed'], role: 'groove_return', accent: false, label: 'Kick (3)', description: 'Steady groove' },
      { beat: 3, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Steady groove' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'hihat_closed'], role: 'groove_return', accent: true, label: 'Snare (4)', description: 'Steady groove' },
      { beat: 4, subdivision: 1, countToken: '&', hand: 'R', surface: 'hihat_closed', accent: false, label: '&', description: 'Steady groove' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Landing on Beat 1 with Crash Cymbal and Bass Drum, and immediately recovering the steady 8th-note groove on Beat 2.',
      howIsItCounted: 'Count "ONE! (Crash) & 2 (Snare) & 3 & 4 &".',
      handsAndFeet: 'Right hand hits Crash, Right foot kicks Bass Drum simultaneously. Right hand returns immediately to Hi-Hat on the "&".',
      drumSurfaces: 'Crash + Kick on 1; Hi-Hat + Snare on 2.',
      musicalApplication: 'A fill is useless if you miss the downbeat landing or stumble coming back into the groove. This is the hallmark of professional playing.',
      whatToListenFor: 'A decisive, thunderous crash and kick landing on beat 1 that locks with the click, followed by zero hesitation on beat 2.',
    },
    commonMistakes: [
      'Hitting the crash without the bass drum (sounds thin and weak)',
      'Hesitating on beat 2 after the crash',
      'Rushing into the crash early and pulling the entire band forward',
    ],
    diagnosticIssues: ['Missed beat 1', 'Lost the groove after the fill', 'Rushed', 'Dragged'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 30,
      standardText: '2 consecutive clean downbeat landings with zero groove disruption',
    },
    recommendedAssistance: 'REDUCED',
    supportsCoachThenYou: true,
  },

  // 13. SINGLE STROKE ROLL
  'comp-rud-singles': {
    id: 'teach-rud-singles',
    competencyId: 'comp-rud-singles',
    skillId: 'rud-single-stroke',
    title: 'Single Stroke Roll (R L R L)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '16th Notes',
    subdivisionCount: 4,
    countTokens: ['1', 'e', '&', 'a', '2', 'e', '&', 'a', '3', 'e', '&', 'a', '4', 'e', '&', 'a'],
    spokenTokens: ['one', 'e', 'and', 'a', 'two', 'e', 'and', 'a', 'three', 'e', 'and', 'a', 'four', 'e', 'and', 'a'],
    sticking: 'R L R L R L R L R L R L R L R L',
    limbPattern: 'Strict alternating hands with identical stick height and velocity',
    drumSurfaces: ['Pad Center', 'Snare Drum'],
    accentPositions: [0, 4, 8, 12],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Downbeat accent' },
      { beat: 1, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 1, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Tap' },
      { beat: 1, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Downbeat accent' },
      { beat: 2, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 2, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Tap' },
      { beat: 2, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Downbeat accent' },
      { beat: 3, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 3, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Tap' },
      { beat: 3, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Downbeat accent' },
      { beat: 4, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
      { beat: 4, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Tap' },
      { beat: 4, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Tap' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Rudiment #1: Alternating single strokes with matched sound quality, dynamic balance, and relaxed wrist mechanics.',
      howIsItCounted: 'Count "1 e & a 2 e & a 3 e & a 4 e & a".',
      handsAndFeet: 'Right hand and Left hand alternating strictly. Full wrist strokes with natural rebound.',
      drumSurfaces: 'Practice pad center or snare drum.',
      musicalApplication: 'The foundation of all drum fills, speed, and orchestral snare playing.',
      whatToListenFor: 'Both hands must sound indistinguishable. No "galloping" or limp rhythm.',
    },
    commonMistakes: [
      'Non-dominant hand playing weaker or lower than dominant hand',
      'Shoulder and bicep tension when pushing tempo',
      'Fingers flying off the stick',
    ],
    diagnosticIssues: ['Uneven notes', 'Tension', 'Wrong sticking', 'Rushed'],
    workingTempo: 70,
    certificationTempo: {
      bpm: 90,
      durationSeconds: 30,
      standardText: '16th notes at 90 BPM for 30 seconds with perfect volume balance',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 14. DOUBLE STROKE ROLL
  'comp-rud-doubles': {
    id: 'teach-rud-doubles',
    competencyId: 'comp-rud-doubles',
    skillId: 'rud-double-stroke',
    title: 'Double Stroke Roll (R R L L)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '16th Notes',
    subdivisionCount: 4,
    countTokens: ['1', 'e', '&', 'a', '2', 'e', '&', 'a', '3', 'e', '&', 'a', '4', 'e', '&', 'a'],
    spokenTokens: ['one', 'e', 'and', 'a', 'two', 'e', 'and', 'a', 'three', 'e', 'and', 'a', 'four', 'e', 'and', 'a'],
    sticking: 'R R L L R R L L R R L L R R L L',
    limbPattern: 'Two strokes per hand: Primary wrist stroke + controlled finger rebound',
    drumSurfaces: ['Pad Center', 'Snare Drum'],
    accentPositions: [0, 4, 8, 12],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'First R stroke' },
      { beat: 1, subdivision: 1, countToken: 'e', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Second R stroke' },
      { beat: 1, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'First L stroke' },
      { beat: 1, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Second L stroke' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'First R stroke' },
      { beat: 2, subdivision: 1, countToken: 'e', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Second R stroke' },
      { beat: 2, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'First L stroke' },
      { beat: 2, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Second L stroke' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'First R stroke' },
      { beat: 3, subdivision: 1, countToken: 'e', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Second R stroke' },
      { beat: 3, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'First L stroke' },
      { beat: 3, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Second L stroke' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'First R stroke' },
      { beat: 4, subdivision: 1, countToken: 'e', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Second R stroke' },
      { beat: 4, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'First L stroke' },
      { beat: 4, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Second L stroke' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Rudiment #2: Playing two clean, articulated strokes per hand. The second stroke must be as loud as the first.',
      howIsItCounted: 'Count "1 e & a 2 e & a". Think "didadida" with zero spacing between hands.',
      handsAndFeet: 'Right-Right, Left-Left. Wrist throws the first note; fingers snap the rebound for the second.',
      drumSurfaces: 'Practice pad center or snare drum.',
      musicalApplication: 'Enables smooth press rolls, six-stroke rolls, and blistering tom fills with minimal physical effort.',
      whatToListenFor: 'The second stroke of each double must not sound like a weak shadow tap. Listen for "da-DA da-DA".',
    },
    commonMistakes: [
      'Second note much softer than the first note (buzzy double)',
      'Crushing the stick into the pad instead of letting it rebound',
      'Left hand double slowing down and destroying the pulse',
    ],
    diagnosticIssues: ['Uneven notes', 'Wrong sticking', 'Tension', 'Dragged'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 30,
      standardText: 'Double strokes at 80 BPM with equal second-stroke clarity',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 15. SINGLE PARADIDDLE
  'comp-rud-single-paradiddle': {
    id: 'teach-rud-paradiddle',
    competencyId: 'comp-rud-single-paradiddle',
    skillId: 'rud-single-paradiddle',
    title: 'Single Paradiddle (>R L R R  >L R L L)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '16th Notes',
    subdivisionCount: 4,
    countTokens: ['1', 'e', '&', 'a', '2', 'e', '&', 'a', '3', 'e', '&', 'a', '4', 'e', '&', 'a'],
    spokenTokens: ['PAR-a-did-dle', 'PAR-a-did-dle', 'PAR-a-did-dle', 'PAR-a-did-dle'],
    sticking: '>R L R R  >L R L L  >R L R R  >L R L L',
    limbPattern: 'Accented single stroke followed by tap and double, flipping lead hand every 4 notes',
    drumSurfaces: ['Pad Center', 'Snare Drum', 'Ride / Hi-Hat'],
    accentPositions: [0, 4, 8, 12],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'PAR (Accent)' },
      { beat: 1, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'A (Tap)' },
      { beat: 1, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'DID (Double 1)' },
      { beat: 1, subdivision: 3, countToken: 'a', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'DLE (Double 2)' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'L', surface: 'pad_center', accent: true, label: '>L', description: 'PAR (Accent)' },
      { beat: 2, subdivision: 1, countToken: 'e', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'A (Tap)' },
      { beat: 2, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'DID (Double 1)' },
      { beat: 2, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'DLE (Double 2)' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'PAR (Accent)' },
      { beat: 3, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'A (Tap)' },
      { beat: 3, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'DID (Double 1)' },
      { beat: 3, subdivision: 3, countToken: 'a', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'DLE (Double 2)' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'L', surface: 'pad_center', accent: true, label: '>L', description: 'PAR (Accent)' },
      { beat: 4, subdivision: 1, countToken: 'e', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'A (Tap)' },
      { beat: 4, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'DID (Double 1)' },
      { beat: 4, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'DLE (Double 2)' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Rudiment #4: The single paradiddle switches your lead hand every 4 notes, unlocking freedom across the entire kit.',
      howIsItCounted: 'Chant: "PAR - a - did - dle, PAR - a - did - dle" (Accenting PAR).',
      handsAndFeet: '>R L R R followed by >L R L L. High stick on the accent (10-12 in), low on the taps (2-3 in).',
      drumSurfaces: 'Pad: accent zone vs center tap. Kit: Right hand on hi-hat/ride, Left hand on snare.',
      musicalApplication: 'Used for funk ghost-note grooves (David Garibaldi), Latin bell patterns, and fluid drum fills.',
      whatToListenFor: 'Clear dynamic contrast between the accent and the 3 unaccented inner notes (at least 3:1 ratio).',
    },
    commonMistakes: [
      'Accenting the "diddle" instead of the first note',
      'No stick-height contrast (playing all 4 notes at the same loud volume)',
      'Hesitating on the hand switch between R and L',
    ],
    diagnosticIssues: ['Wrong sticking', 'Uneven notes', 'Tension', 'Rushed'],
    workingTempo: 65,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 30,
      standardText: 'Paradiddles at 80 BPM with distinct 3:1 accent-to-tap contrast',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 16. TRIPLETS
  'comp-subdiv-triplets': {
    id: 'teach-triplets',
    competencyId: 'comp-subdiv-triplets',
    skillId: 'subdiv-triplets',
    title: 'Eighth-Note Triplets (1-trip-let 2-trip-let)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: 'Triplets',
    subdivisionCount: 3,
    countTokens: ['1', 'trip', 'let', '2', 'trip', 'let', '3', 'trip', 'let', '4', 'trip', 'let'],
    spokenTokens: ['one', 'trip', 'let', 'two', 'trip', 'let', 'three', 'trip', 'let', 'four', 'trip', 'let'],
    sticking: 'R L R  L R L  R L R  L R L',
    limbPattern: 'Strict 3-note groupings per beat, alternating lead hand each beat',
    drumSurfaces: ['Pad Center', 'Snare Drum', 'Ride Cymbal'],
    accentPositions: [0, 3, 6, 9],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>R (1)', description: 'Beat 1 Accent' },
      { beat: 1, subdivision: 1, countToken: 'trip', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Inner note' },
      { beat: 1, subdivision: 2, countToken: 'let', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Inner note' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'L', surface: 'pad_center', accent: true, label: '>L (2)', description: 'Beat 2 Accent' },
      { beat: 2, subdivision: 1, countToken: 'trip', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Inner note' },
      { beat: 2, subdivision: 2, countToken: 'let', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Inner note' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: true, label: '>R (3)', description: 'Beat 3 Accent' },
      { beat: 3, subdivision: 1, countToken: 'trip', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Inner note' },
      { beat: 3, subdivision: 2, countToken: 'let', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Inner note' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'L', surface: 'pad_center', accent: true, label: '>L (4)', description: 'Beat 4 Accent' },
      { beat: 4, subdivision: 1, countToken: 'trip', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Inner note' },
      { beat: 4, subdivision: 2, countToken: 'let', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Inner note' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Dividing each quarter-note beat into three mathematically identical pieces.',
      howIsItCounted: 'Count "1 - trip - let, 2 - trip - let, 3 - trip - let, 4 - trip - let".',
      handsAndFeet: 'Notice that the lead hand alternates every beat: Beat 1 is R, Beat 2 is L, Beat 3 is R, Beat 4 is L.',
      drumSurfaces: 'Practice pad center, snare drum, or ride cymbal.',
      musicalApplication: 'Essential for blues shuffles, jazz swing, gospel chops, and classic rock fills.',
      whatToListenFor: 'A smooth rolling circular feel. Never let it sound like an 8th and two 16ths (no gallop).',
    },
    commonMistakes: [
      'Playing a straight 8th + two 16ths instead of a true triplet',
      'Dragging the "let" note before the next click',
      'Struggling when Beat 2 begins on the left hand',
    ],
    diagnosticIssues: ['Uneven notes', 'Wrong sticking', 'Lost pulse', 'Dragged'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 75,
      durationSeconds: 30,
      standardText: '8th triplets at 75 BPM with smooth alternating lead',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 17. 6/8 TIME & COMPOUND METER
  'comp-meter-68': {
    id: 'teach-meter-68',
    competencyId: 'comp-meter-68',
    skillId: 'meter-68',
    title: '6/8 Time & Compound Meter',
    meter: '6/8',
    beatsPerBar: 6,
    subdivision: '6/8 Compound',
    subdivisionCount: 1,
    countTokens: ['1', '2', '3', '4', '5', '6'],
    spokenTokens: ['ONE', 'two', 'three', 'FOUR', 'five', 'six'],
    sticking: 'R L R  L R L',
    limbPattern: 'Strong pulse on 1 and 4 (dotted quarter pulse), secondary pulses on 2,3 and 5,6',
    drumSurfaces: ['Kick', 'Snare', 'Ride Cymbal', 'Hi-Hat'],
    accentPositions: [0, 3], // Beats 1 and 4 accented!
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'BOTH', surface: 'kick', surfaces: ['kick', 'ride'], accent: true, label: '>KICK (1)', description: 'Primary macro downbeat (Pulse 1)' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'ride', accent: false, label: 'Ride (2)', description: 'Micro 2' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'ride', accent: false, label: 'Ride (3)', description: 'Micro 3' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'BOTH', surface: 'snare', surfaces: ['snare', 'ride'], accent: true, label: '>SNARE (4)', description: 'Secondary macro downbeat (Pulse 2)' },
      { beat: 5, subdivision: 0, countToken: '5', hand: 'R', surface: 'ride', accent: false, label: 'Ride (5)', description: 'Micro 5' },
      { beat: 6, subdivision: 0, countToken: '6', hand: 'R', surface: 'ride', accent: false, label: 'Ride (6)', description: 'Micro 6' },
    ],
    musicalExplanation: {
      whatAmILearning: '6/8 time has 6 eighth-note pulses per measure, grouped into two big pulses on Beats 1 and 4.',
      howIsItCounted: 'Count "ONE - two - three, FOUR - five - six" with heavy vocal stress on 1 and 4.',
      handsAndFeet: 'Kick lands on Beat 1; Snare backbeat lands on Beat 4. Ride cymbal taps continuously on all 6 beats.',
      drumSurfaces: 'Kick (1), Snare (4), Ride Cymbal (1-6).',
      musicalApplication: 'Dominates modern worship ballads (Hillsong, Bethel), blues rock, and African 12/8 rhythms.',
      whatToListenFor: 'The heavy sway between Beat 1 and Beat 4. It should feel like two swaying pendulum swings, not six rigid robotic clicks.',
    },
    commonMistakes: [
      'Counting as 3/4 time (three groups of two) instead of two groups of three',
      'Weak or missed snare hit on Beat 4',
      'Rushing the micro-notes 2, 3 and 5, 6',
    ],
    diagnosticIssues: ['Lost pulse', 'Rushed', 'Missed beat 1', 'Uneven notes'],
    workingTempo: 50,
    certificationTempo: {
      bpm: 65,
      durationSeconds: 40,
      standardText: '16 bars of 6/8 ballad groove at 65 BPM with authoritative 1 & 4 accents',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 18. R-L-K LINEAR PHRASE
  'comp-coord-rlk': {
    id: 'teach-coord-rlk',
    competencyId: 'comp-coord-rlk',
    skillId: 'coord-rlk',
    title: 'R-L-K Linear Phrase (Hand-Foot Triplet Flow)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: 'Triplets',
    subdivisionCount: 3,
    countTokens: ['1', 'trip', 'let', '2', 'trip', 'let', '3', 'trip', 'let', '4', 'trip', 'let'],
    spokenTokens: ['R', 'L', 'Kick', 'R', 'L', 'Kick', 'R', 'L', 'Kick', 'R', 'L', 'Kick'],
    sticking: 'R L K  R L K  R L K  R L K',
    limbPattern: 'Linear hand-to-foot coordination: No two limbs strike simultaneously',
    drumSurfaces: ['High Tom', 'Snare', 'Kick', 'Floor Tom'],
    accentPositions: [0, 3, 6, 9],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'tom_high', accent: true, label: '>R', description: 'High Tom' },
      { beat: 1, subdivision: 1, countToken: 'trip', hand: 'L', surface: 'snare', accent: false, label: 'L', description: 'Snare tap' },
      { beat: 1, subdivision: 2, countToken: 'let', hand: 'K', surface: 'kick', accent: false, label: 'K', description: 'Kick drum' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'tom_high', accent: true, label: '>R', description: 'High Tom' },
      { beat: 2, subdivision: 1, countToken: 'trip', hand: 'L', surface: 'snare', accent: false, label: 'L', description: 'Snare tap' },
      { beat: 2, subdivision: 2, countToken: 'let', hand: 'K', surface: 'kick', accent: false, label: 'K', description: 'Kick drum' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'tom_floor', accent: true, label: '>R', description: 'Floor Tom' },
      { beat: 3, subdivision: 1, countToken: 'trip', hand: 'L', surface: 'snare', accent: false, label: 'L', description: 'Snare tap' },
      { beat: 3, subdivision: 2, countToken: 'let', hand: 'K', surface: 'kick', accent: false, label: 'K', description: 'Kick drum' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'tom_floor', accent: true, label: '>R', description: 'Floor Tom' },
      { beat: 4, subdivision: 1, countToken: 'trip', hand: 'L', surface: 'snare', accent: false, label: 'L', description: 'Snare tap' },
      { beat: 4, subdivision: 2, countToken: 'let', hand: 'K', surface: 'kick', accent: false, label: 'K', description: 'Kick drum' },
    ],
    musicalExplanation: {
      whatAmILearning: 'Linear drumming means no two limbs hit at the exact same moment. R-L-K combines two hands and a bass drum into fluid gospel/rock fills.',
      howIsItCounted: 'Sing the limbs: "Right - Left - Kick, Right - Left - Kick".',
      handsAndFeet: 'Right hand -> Left hand -> Right foot. Loop continuously without any micro-pauses.',
      drumSurfaces: 'High Tom (R) -> Snare (L) -> Kick (K). Move to Floor Tom on beats 3 and 4.',
      musicalApplication: 'The cornerstone of modern gospel chops, Vinnie Colaiuta fills, and fusion drumming.',
      whatToListenFor: 'Complete linear spacing. The kick drum note must have the exact same volume and time distance as the stick hits.',
    },
    commonMistakes: [
      'Kick drum rushing and overlapping with the left hand',
      'Weak bass drum volume compared to the hands',
      'Stumbling when orchestrating the right hand to the floor tom',
    ],
    diagnosticIssues: ['Kick coordination', 'Uneven notes', 'Rushed', 'Tension'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 30,
      standardText: 'Continuous R-L-K triplets at 80 BPM with perfect hand-foot balance',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 19. SIX STROKE ROLL
  'comp-rud-six-stroke': {
    id: 'teach-six-stroke',
    competencyId: 'comp-rud-six-stroke',
    skillId: 'rud-six-stroke',
    title: 'Six Stroke Roll (>R L L R R >L)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '16th Notes',
    subdivisionCount: 6,
    countTokens: ['1', 'e', '&', 'a', 'ta', 'la', '2', 'e', '&', 'a', 'ta', 'la'],
    spokenTokens: ['ONE', 'e', 'and', 'a', 'ta', 'LA', 'TWO', 'e', 'and', 'a', 'ta', 'LA'],
    sticking: '>R L L R R >L',
    limbPattern: 'Accented lead stroke, two inner doubles, resolving with an accented trailing stroke',
    drumSurfaces: ['Snare Drum', 'High Tom', 'Floor Tom'],
    accentPositions: [0, 5],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'First Accent (>R)' },
      { beat: 1, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Inner double (L)' },
      { beat: 1, subdivision: 2, countToken: '&', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Inner double (L)' },
      { beat: 1, subdivision: 3, countToken: 'a', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Inner double (R)' },
      { beat: 1, subdivision: 4, countToken: 'ta', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Inner double (R)' },
      { beat: 1, subdivision: 5, countToken: 'la', hand: 'L', surface: 'pad_center', accent: true, label: '>L', description: 'Second Accent (>L)' },
    ],
    musicalExplanation: {
      whatAmILearning: 'One of the most expressive rudiments in drumming: an accented single, two quiet doubles, and a closing accented single.',
      howIsItCounted: 'Count as sextuplets: "1 e & a ta la" or chant "DIG-ga-da-dig-ga-DAT".',
      handsAndFeet: '>R (accent) L L (taps) R R (taps) >L (accent).',
      drumSurfaces: 'Snare, or orchestrate >R on High Tom and >L on Floor Tom with doubles in center snare.',
      musicalApplication: 'Steve Gadd, Chad Smith, and Tony Williams rely heavily on this rudiment for soulful, lightning-fast fills.',
      whatToListenFor: 'Extreme dynamic separation: the inner doubles must whisper while the two accents pop with authority.',
    },
    commonMistakes: [
      'Inner doubles played too loudly, drowning out the accents',
      'Dragging the second accent on the left hand',
      'Losing count of the 6-note sextuplet grid',
    ],
    diagnosticIssues: ['Uneven notes', 'Wrong sticking', 'Tension', 'Missed beat 1'],
    workingTempo: 60,
    certificationTempo: {
      bpm: 80,
      durationSeconds: 30,
      standardText: 'Six-stroke rolls at 80 BPM with dramatic accent-to-tap contrast',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },

  // 20. 32ND-NOTE SUBDIVISION
  'comp-subdiv-32nd': {
    id: 'teach-subdiv-32nd',
    competencyId: 'comp-subdiv-32nd',
    skillId: 'subdiv-32nd',
    title: '32nd-Note Subdivision (8 Notes Per Beat)',
    meter: '4/4',
    beatsPerBar: 4,
    subdivision: '32nd Notes',
    subdivisionCount: 8,
    countTokens: ['1', 'e', '&', 'a', '+', 'e', '&', 'a', '2', 'e', '&', 'a', '+', 'e', '&', 'a', '3', 'e', '&', 'a', '+', 'e', '&', 'a', '4', 'e', '&', 'a', '+', 'e', '&', 'a'],
    spokenTokens: ['1', 'e', 'and', 'a', 'and', 'e', 'and', 'a', '2', 'e', 'and', 'a', 'and', 'e', 'and', 'a', '3', 'e', 'and', 'a', 'and', 'e', 'and', 'a', '4', 'e', 'and', 'a', 'and', 'e', 'and', 'a'],
    sticking: 'R L R L R L R L — eight strokes per quarter-note beat',
    limbPattern: 'Alternating hands with eight evenly spaced strokes inside every quarter-note beat',
    drumSurfaces: ['Pad Center', 'Snare Drum'],
    accentPositions: [0, 8, 16, 24],
    bars: 1,
    events: [
      { beat: 1, subdivision: 0, countToken: '1', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Beat 1 — 32nd subdivision 1/8' },
      { beat: 1, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 1 — 32nd subdivision 2/8' },
      { beat: 1, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 1 — 32nd subdivision 3/8' },
      { beat: 1, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 1 — 32nd subdivision 4/8' },
      { beat: 1, subdivision: 4, countToken: '+', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 1 — 32nd subdivision 5/8' },
      { beat: 1, subdivision: 5, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 1 — 32nd subdivision 6/8' },
      { beat: 1, subdivision: 6, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 1 — 32nd subdivision 7/8' },
      { beat: 1, subdivision: 7, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 1 — 32nd subdivision 8/8' },
      { beat: 2, subdivision: 0, countToken: '2', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Beat 2 — 32nd subdivision 1/8' },
      { beat: 2, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 2 — 32nd subdivision 2/8' },
      { beat: 2, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 2 — 32nd subdivision 3/8' },
      { beat: 2, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 2 — 32nd subdivision 4/8' },
      { beat: 2, subdivision: 4, countToken: '+', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 2 — 32nd subdivision 5/8' },
      { beat: 2, subdivision: 5, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 2 — 32nd subdivision 6/8' },
      { beat: 2, subdivision: 6, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 2 — 32nd subdivision 7/8' },
      { beat: 2, subdivision: 7, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 2 — 32nd subdivision 8/8' },
      { beat: 3, subdivision: 0, countToken: '3', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Beat 3 — 32nd subdivision 1/8' },
      { beat: 3, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 3 — 32nd subdivision 2/8' },
      { beat: 3, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 3 — 32nd subdivision 3/8' },
      { beat: 3, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 3 — 32nd subdivision 4/8' },
      { beat: 3, subdivision: 4, countToken: '+', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 3 — 32nd subdivision 5/8' },
      { beat: 3, subdivision: 5, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 3 — 32nd subdivision 6/8' },
      { beat: 3, subdivision: 6, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 3 — 32nd subdivision 7/8' },
      { beat: 3, subdivision: 7, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 3 — 32nd subdivision 8/8' },
      { beat: 4, subdivision: 0, countToken: '4', hand: 'R', surface: 'pad_center', accent: true, label: '>R', description: 'Beat 4 — 32nd subdivision 1/8' },
      { beat: 4, subdivision: 1, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 4 — 32nd subdivision 2/8' },
      { beat: 4, subdivision: 2, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 4 — 32nd subdivision 3/8' },
      { beat: 4, subdivision: 3, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 4 — 32nd subdivision 4/8' },
      { beat: 4, subdivision: 4, countToken: '+', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 4 — 32nd subdivision 5/8' },
      { beat: 4, subdivision: 5, countToken: 'e', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 4 — 32nd subdivision 6/8' },
      { beat: 4, subdivision: 6, countToken: '&', hand: 'R', surface: 'pad_center', accent: false, label: 'R', description: 'Beat 4 — 32nd subdivision 7/8' },
      { beat: 4, subdivision: 7, countToken: 'a', hand: 'L', surface: 'pad_center', accent: false, label: 'L', description: 'Beat 4 — 32nd subdivision 8/8' },
    ],
    musicalExplanation: {
      whatAmILearning: '32nd notes divide each quarter-note beat into eight equal spaces. The goal is not raw speed: every one of the eight notes must fit evenly before the next beat arrives.',
      howIsItCounted: 'Keep saying the main beat number strongly, then use two groups of four syllables inside it: “1 e & a + e & a; 2 e & a + e & a…” The visual grid shows all eight spaces.',
      handsAndFeet: 'Use low alternating hand strokes. Keep the forearms relaxed and let fingers control the rebound.',
      drumSurfaces: 'Practice pad first; later move controlled bursts to snare, hi-hat, or orchestrated fills.',
      musicalApplication: 'Short 32nd-note bursts can add intensity to fills and embellishments, but only when the underlying quarter-note pulse remains stable.',
      whatToListenFor: 'Eight equal spaces per beat. Avoid bunching the middle notes or rushing the final two strokes into the next click.',
    },
    commonMistakes: [
      'Tensing the arms into a buzz instead of eight articulated strokes',
      'Rushing the final notes before the next quarter-note beat',
      'Losing awareness of the main 1-2-3-4 pulse',
    ],
    diagnosticIssues: ['Tension', 'Rushed', 'Uneven notes', 'Lost pulse'],
    workingTempo: 45,
    certificationTempo: {
      bpm: 60,
      durationSeconds: 20,
      standardText: 'Controlled 32nd-note subdivision at 60 BPM with eight even notes per beat and relaxed hands',
    },
    recommendedAssistance: 'FULL',
    supportsCoachThenYou: true,
  },
};

/**
 * Finds a teaching definition without silently substituting a different skill.
 * This is important for curriculum integrity: an unknown exercise must never
 * masquerade as Quarter-Note Pulse simply because a definition is missing.
 */
export function findTeachingDefinition(identifier: string): CompetencyTeachingDefinition | null {
  if (!identifier) return null;
  if (TEACHING_DEFINITIONS[identifier]) return TEACHING_DEFINITIONS[identifier];

  for (const def of Object.values(TEACHING_DEFINITIONS)) {
    if (def.skillId === identifier || def.id === identifier) return def;
  }

  const lower = identifier.toLowerCase();
  if (lower.includes('quarter') && lower.includes('pulse')) return TEACHING_DEFINITIONS['comp-pulse-quarter'];
  if ((lower.includes('8th') || lower.includes('eighth')) && lower.includes('subdiv')) return TEACHING_DEFINITIONS['comp-subdiv-8th'];
  if (lower.includes('4/4') || lower.includes('bar structure') || lower.includes('bar-structure')) return TEACHING_DEFINITIONS['comp-meter-44'];
  if (lower.includes('backbeat')) return TEACHING_DEFINITIONS['comp-grv-backbeat'];
  if (lower.includes('groove') && lower.includes('stability')) return TEACHING_DEFINITIONS['comp-grv-stability'];
  if (lower.includes('kick') && lower.includes('variation')) return TEACHING_DEFINITIONS['comp-grv-kick-variation'];
  if (lower.includes('paradiddle')) return TEACHING_DEFINITIONS['comp-rud-single-paradiddle'];
  if (lower.includes('single') && lower.includes('stroke')) return TEACHING_DEFINITIONS['comp-rud-singles'];
  if (lower.includes('double') && lower.includes('stroke')) return TEACHING_DEFINITIONS['comp-rud-doubles'];
  if (lower.includes('six') && lower.includes('stroke')) return TEACHING_DEFINITIONS['comp-rud-six-stroke'];
  if (lower.includes('triplet')) return TEACHING_DEFINITIONS['comp-subdiv-triplets'];
  if (lower.includes('6/8') || lower.includes('68')) return TEACHING_DEFINITIONS['comp-meter-68'];
  if (lower.includes('r-l-k') || lower.includes('rlk')) return TEACHING_DEFINITIONS['comp-coord-rlk'];
  if (lower.includes('32nd')) return TEACHING_DEFINITIONS['comp-subdiv-32nd'];
  if (lower.includes('recovery')) return TEACHING_DEFINITIONS['comp-fill-recovery'];
  if (lower.includes('groove-to-fill') || lower.includes('fill entry') || lower.includes('entry')) return TEACHING_DEFINITIONS['comp-fill-entry'];
  if (lower.includes('fill') && (lower.includes('16th') || lower.includes('sixteenth'))) return TEACHING_DEFINITIONS['comp-fill-16th'];
  if (lower.includes('fill') && (lower.includes('8th') || lower.includes('eighth'))) return TEACHING_DEFINITIONS['comp-fill-8th'];
  if (lower.includes('fill') && lower.includes('quarter')) return TEACHING_DEFINITIONS['comp-fill-quarter'];
  if (lower.includes('notation')) return TEACHING_DEFINITIONS['comp-reading-notation'];
  return null;
}

/**
 * Backwards-compatible lookup for callers that require a definition.
 * New curriculum-aware code should prefer findTeachingDefinition() when a
 * silent fallback would be misleading.
 */
export function getTeachingDefinition(identifier: string): CompetencyTeachingDefinition {
  return findTeachingDefinition(identifier) || TEACHING_DEFINITIONS['comp-pulse-quarter'];
}
